spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  #        generate_statistics: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/poster
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

bot:
  token: 936900762:AAFmt_XLat6n4XwfZbtRBev7MxO_tX7wz04
  channelId: -1001359577803